name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build
        env:
          NODE_ENV: production
          # Set your domain for proper asset paths
          NEXT_PUBLIC_BASE_URL: https://tbritt.xyz

      - name: Debug output directory
        run: |
            echo "Listing output directory contents:"
            ls -la ./out
            echo "Checking for specific images:"
            find ./out -name "*.png" -o -name "*.jpg" -o -name "*.svg" | sort

      - name: Copy images to output directory
        run: |
          echo "Ensuring images directory exists in output"
          mkdir -p ./out/images
          
          # Copy all image files from public to out
          echo "Copying images from public directory to out directory"
          cp -rv ./public/*.png ./public/*.jpg ./public/*.svg ./public/*.ico ./out/ 2>/dev/null || true
          
          # List the output directory after copying
          echo "Output directory after copying images:"
          ls -la ./out
          echo "Image files in output:"
          find ./out -name "*.png" -o -name "*.jpg" -o -name "*.svg" -o -name "*.ico" | sort

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./out

      - name: Debug downloaded artifacts
        run: |
            echo "Listing downloaded artifacts:"
            ls -la ./out
            echo "Checking for specific images:"
            find ./out -name "*.png" -o -name "*.jpg" -o -name "*.svg" | sort

      - name: add-domain-cname
        run: |
          # Create CNAME file
          echo "tbritt.xyz" > ./out/CNAME
          # Create .nojekyll file to prevent Jekyll processing
          touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true